'use client';
import { useUIContext } from '@/contexts/UIContext';
import { useAuthContext } from '@/contexts/AuthContext';
import { useOneDriveContext } from '@/contexts/OneDriveContext';
import { useFirestoreContext } from '@/contexts/FirestoreContext';
import { useInventoryContext } from '@/contexts/InventoryContext';
import { useGalleryContext } from '@/contexts/GalleryContext';
import { useTimeTrackingContext } from '@/contexts/TimeTrackingContext';
import { useCalendarContext } from '@/contexts/CalendarContext';
import { useInvoiceContext } from '@/contexts/InvoiceContext';
import { useChatContext } from '@/contexts/ChatContext';
import { useNotifContext } from '@/contexts/NotifContext';

/**
 * Compatibility hook that combines all 6 specialized contexts.
 * Returns the exact same interface as the old monolithic AppContext.
 * Consumer files do NOT need to change — they still import { useApp } from '@/contexts/AppContext'.
 */
export function useApp() {
  const ui = useUIContext();
  const auth = useAuthContext();
  const od = useOneDriveContext();
  const fs = useFirestoreContext();
  const inv = useInventoryContext();
  const gal = useGalleryContext();
  const tt = useTimeTrackingContext();
  const cal = useCalendarContext();
  const invCtx = useInvoiceContext();
  const chat = useChatContext();
  const notif = useNotifContext();

  return {
    // ===== UI =====
    screen: ui.screen,
    setScreen: ui.setScreen,
    selectedProjectId: ui.selectedProjectId,
    setSelectedProjectId: ui.setSelectedProjectId,
    selectedCompanyId: ui.selectedCompanyId,
    setSelectedCompanyId: ui.setSelectedCompanyId,
    navigateTo: ui.navigateTo,
    navigateToRef: ui.navigateToRef,
    sidebarOpen: ui.sidebarOpen,
    setSidebarOpen: ui.setSidebarOpen,
    sidebarCollapsed: ui.sidebarCollapsed,
    setSidebarCollapsed: ui.setSidebarCollapsed,
    chatMobileShow: ui.chatMobileShow,
    setChatMobileShow: ui.setChatMobileShow,
    taskViewMode: ui.taskViewMode,
    setTaskViewMode: ui.setTaskViewMode,
    darkMode: ui.darkMode,
    setDarkMode: ui.setDarkMode,
    toggleTheme: ui.toggleTheme,
    installPrompt: ui.installPrompt,
    setInstallPrompt: ui.setInstallPrompt,
    showInstallBanner: ui.showInstallBanner,
    setShowInstallBanner: ui.setShowInstallBanner,
    isInstalled: ui.isInstalled,
    setIsInstalled: ui.setIsInstalled,
    showInstallGuide: ui.showInstallGuide,
    setShowInstallGuide: ui.setShowInstallGuide,
    isStandalone: ui.isStandalone,
    handleInstall: ui.handleInstall,
    dismissInstallBanner: ui.dismissInstallBanner,
    platform: ui.platform,
    modals: ui.modals,
    setModals: ui.setModals,
    editingId: ui.editingId,
    setEditingId: ui.setEditingId,
    openModal: ui.openModal,
    closeModal: ui.closeModal,
    forms: ui.forms,
    setForms: ui.setForms,
    showToast: ui.showToast,
    screenTitles: ui.screenTitles,

    // ===== AUTH =====
    ready: auth.ready,
    setReady: auth.setReady,
    authUser: auth.authUser,
    setAuthUser: auth.setAuthUser,
    loading: auth.loading,
    setLoading: auth.setLoading,
    teamUsers: auth.teamUsers,
    doLogin: auth.doLogin,
    doRegister: auth.doRegister,
    doGoogleLogin: auth.doGoogleLogin,
    doMicrosoftLogin: auth.doMicrosoftLogin,
    doLogout: auth.doLogout,
    getMyRole: auth.getMyRole,
    getMyCompanyId: auth.getMyCompanyId,
    visibleProjects: auth.visibleProjects,
    getUserName: auth.getUserName,
    updateUserRole: auth.updateUserRole,
    updateUserCompany: auth.updateUserCompany,
    userName: auth.userName,
    initials: auth.initials,
    myRole: auth.myRole,
    isAdmin: auth.isAdmin,
    isEmailAdmin: auth.isEmailAdmin,
    getUserRole: auth.getUserRole,

    // ===== ONEDRIVE =====
    msAccessToken: od.msAccessToken,
    setMsAccessToken: od.setMsAccessToken,
    msConnected: od.msConnected,
    setMsConnected: od.setMsConnected,
    msLoading: od.msLoading,
    setMsLoading: od.setMsLoading,
    oneDriveFiles: od.oneDriveFiles,
    setOneDriveFiles: od.setOneDriveFiles,
    odProjectFolder: od.odProjectFolder,
    setOdProjectFolder: od.setOdProjectFolder,
    showOneDrive: od.showOneDrive,
    setShowOneDrive: od.setShowOneDrive,
    msRefreshToken: od.msRefreshToken,
    setMsRefreshToken: od.setMsRefreshToken,
    msTokenExpiry: od.msTokenExpiry,
    setMsTokenExpiry: od.setMsTokenExpiry,
    odSearchQuery: od.odSearchQuery,
    setOdSearchQuery: od.setOdSearchQuery,
    odSearchResults: od.odSearchResults,
    setOdSearchResults: od.setOdSearchResults,
    odSearching: od.odSearching,
    setOdSearching: od.setOdSearching,
    odBreadcrumbs: od.odBreadcrumbs,
    setOdBreadcrumbs: od.setOdBreadcrumbs,
    odCurrentFolder: od.odCurrentFolder,
    setOdCurrentFolder: od.setOdCurrentFolder,
    odViewMode: od.odViewMode,
    setOdViewMode: od.setOdViewMode,
    odRenaming: od.odRenaming,
    setOdRenaming: od.setOdRenaming,
    odRenameName: od.odRenameName,
    setOdRenameName: od.setOdRenameName,
    odUploading: od.odUploading,
    setOdUploading: od.setOdUploading,
    odUploadProgress: od.odUploadProgress,
    setOdUploadProgress: od.setOdUploadProgress,
    odUploadFile: od.odUploadFile,
    setOdUploadFile: od.setOdUploadFile,
    odDragOver: od.odDragOver,
    setOdDragOver: od.setOdDragOver,
    odTab: od.odTab,
    setOdTab: od.setOdTab,
    galleryLoading: od.galleryLoading,
    setGalleryLoading: od.setGalleryLoading,
    odGalleryPhotos: od.odGalleryPhotos,
    setOdGalleryPhotos: od.setOdGalleryPhotos,
    disconnectMicrosoft: od.disconnectMicrosoft,
    refreshMsToken: od.refreshMsToken,
    graphApiGet: od.graphApiGet,
    ensureProjectFolder: od.ensureProjectFolder,
    loadOneDriveFiles: od.loadOneDriveFiles,
    uploadToOneDrive: od.uploadToOneDrive,
    deleteFromOneDrive: od.deleteFromOneDrive,
    openOneDriveForProject: od.openOneDriveForProject,
    formatFileSize: od.formatFileSize,
    timeAgo: od.timeAgo,
    getFileIcon: od.getFileIcon,
    navigateToFolder: od.navigateToFolder,
    uploadFileWithProgress: od.uploadFileWithProgress,
    handleFileUpload: od.handleFileUpload,
    handleDroppedFiles: od.handleDroppedFiles,
    renameOneDriveFile: od.renameOneDriveFile,
    downloadOneDriveFile: od.downloadOneDriveFile,
    searchOneDriveFiles: od.searchOneDriveFiles,
    loadGalleryPhotos: od.loadGalleryPhotos,

    // ===== FIRESTORE =====
    projects: fs.projects,
    setProjects: fs.setProjects,
    tasks: fs.tasks,
    setTasks: fs.setTasks,
    expenses: fs.expenses,
    setExpenses: fs.setExpenses,
    suppliers: fs.suppliers,
    setSuppliers: fs.setSuppliers,
    companies: fs.companies,
    setCompanies: fs.setCompanies,
    workPhases: fs.workPhases,
    setWorkPhases: fs.setWorkPhases,
    projectFiles: fs.projectFiles,
    setProjectFiles: fs.setProjectFiles,
    approvals: fs.approvals,
    setApprovals: fs.setApprovals,
    meetings: cal.meetings,
    setMeetings: cal.setMeetings,
    galleryPhotos: gal.galleryPhotos,
    setGalleryPhotos: gal.setGalleryPhotos,
    invProducts: inv.invProducts,
    setInvProducts: inv.setInvProducts,
    invCategories: inv.invCategories,
    setInvCategories: inv.setInvCategories,
    invMovements: inv.invMovements,
    setInvMovements: inv.setInvMovements,
    invTransfers: inv.invTransfers,
    setInvTransfers: inv.setInvTransfers,
    timeEntries: tt.timeEntries,
    setTimeEntries: tt.setTimeEntries,
    comments: fs.comments,
    setComments: fs.setComments,
    dailyLogs: fs.dailyLogs,
    setDailyLogs: fs.setDailyLogs,

    // Domain UI — Calendar
    calMonth: cal.calMonth,
    setCalMonth: cal.setCalMonth,
    calYear: cal.calYear,
    setCalYear: cal.setCalYear,
    calSelectedDate: cal.calSelectedDate,
    setCalSelectedDate: cal.setCalSelectedDate,
    calFilterProject: cal.calFilterProject,
    setCalFilterProject: cal.setCalFilterProject,

    // Domain UI — Gallery
    galleryFilterProject: gal.galleryFilterProject,
    setGalleryFilterProject: gal.setGalleryFilterProject,
    galleryFilterCat: gal.galleryFilterCat,
    setGalleryFilterCat: gal.setGalleryFilterCat,
    lightboxPhoto: gal.lightboxPhoto,
    setLightboxPhoto: gal.setLightboxPhoto,
    lightboxIndex: gal.lightboxIndex,
    setLightboxIndex: gal.setLightboxIndex,

    // Domain UI — Inventory
    invTab: inv.invTab,
    setInvTab: inv.setInvTab,
    invFilterCat: inv.invFilterCat,
    setInvFilterCat: inv.setInvFilterCat,
    invSearch: inv.invSearch,
    setInvSearch: inv.setInvSearch,
    invMovFilterType: inv.invMovFilterType,
    setInvMovFilterType: inv.setInvMovFilterType,
    invTransferFilterStatus: inv.invTransferFilterStatus,
    setInvTransferFilterStatus: inv.setInvTransferFilterStatus,
    invWarehouseFilter: inv.invWarehouseFilter,
    setInvWarehouseFilter: inv.setInvWarehouseFilter,

    // Domain UI — Time Tracking
    timeTab: tt.timeTab,
    setTimeTab: tt.setTimeTab,
    timeFilterProject: tt.timeFilterProject,
    setTimeFilterProject: tt.setTimeFilterProject,
    timeFilterDate: tt.timeFilterDate,
    setTimeFilterDate: tt.setTimeFilterDate,
    timeSession: tt.timeSession,
    setTimeSession: tt.setTimeSession,
    timeTimerMs: tt.timeTimerMs,
    setTimeTimerMs: tt.setTimeTimerMs,

    // Domain UI — Invoices
    invoices: invCtx.invoices,
    setInvoices: invCtx.setInvoices,
    invoiceTab: invCtx.invoiceTab,
    setInvoiceTab: invCtx.setInvoiceTab,
    invoiceItems: invCtx.invoiceItems,
    setInvoiceItems: invCtx.setInvoiceItems,
    invoiceFilterStatus: invCtx.invoiceFilterStatus,
    setInvoiceFilterStatus: invCtx.setInvoiceFilterStatus,

    // Domain UI — Comments
    commentText: fs.commentText,
    setCommentText: fs.setCommentText,
    replyingTo: fs.replyingTo,
    setReplyingTo: fs.setReplyingTo,

    // Domain UI — Daily Logs
    dailyLogTab: fs.dailyLogTab,
    setDailyLogTab: fs.setDailyLogTab,
    selectedLogId: fs.selectedLogId,
    setSelectedLogId: fs.setSelectedLogId,
    logForm: fs.logForm,
    setLogForm: fs.setLogForm,

    // Domain UI — Admin
    adminTab: fs.adminTab,
    setAdminTab: fs.setAdminTab,
    adminWeekOffset: fs.adminWeekOffset,
    setAdminWeekOffset: fs.setAdminWeekOffset,
    adminTaskSearch: fs.adminTaskSearch,
    setAdminTaskSearch: fs.setAdminTaskSearch,
    adminFilterAssignee: fs.adminFilterAssignee,
    setAdminFilterAssignee: fs.setAdminFilterAssignee,
    adminFilterProject: fs.adminFilterProject,
    setAdminFilterProject: fs.setAdminFilterProject,
    adminFilterPriority: fs.adminFilterPriority,
    setAdminFilterPriority: fs.setAdminFilterPriority,
    adminTooltipTask: fs.adminTooltipTask,
    setAdminTooltipTask: fs.setAdminTooltipTask,
    adminTooltipPos: fs.adminTooltipPos,
    setAdminTooltipPos: fs.setAdminTooltipPos,
    adminPermSection: fs.adminPermSection,
    setAdminPermSection: fs.setAdminPermSection,
    rolePerms: fs.rolePerms,
    setRolePerms: fs.setRolePerms,
    toggleRolePerm: fs.toggleRolePerm,

    // Firestore CRUD
    saveProject: fs.saveProject,
    deleteProject: fs.deleteProject,
    openEditProject: fs.openEditProject,
    updateProjectProgress: fs.updateProjectProgress,
    updateUserName: fs.updateUserName,
    toggleTask: fs.toggleTask,
    changeTaskStatus: fs.changeTaskStatus,
    deleteTask: fs.deleteTask,
    saveExpense: fs.saveExpense,
    deleteExpense: fs.deleteExpense,
    saveSupplier: fs.saveSupplier,
    deleteSupplier: fs.deleteSupplier,
    saveCompany: fs.saveCompany,
    uploadFile: fs.uploadFile,
    deleteFile: fs.deleteFile,
    initDefaultPhases: fs.initDefaultPhases,
    updatePhaseStatus: fs.updatePhaseStatus,
    saveApproval: fs.saveApproval,
    updateApproval: fs.updateApproval,
    deleteApproval: fs.deleteApproval,
    saveDailyLog: fs.saveDailyLog,
    deleteDailyLog: fs.deleteDailyLog,
    openEditLog: fs.openEditLog,
    resetLogForm: fs.resetLogForm,
    getWarehouseStock: inv.getWarehouseStock,
    getTotalStock: inv.getTotalStock,
    buildWarehouseStock: inv.buildWarehouseStock,
    saveInvProduct: inv.saveInvProduct,
    deleteInvProduct: inv.deleteInvProduct,
    openEditInvProduct: inv.openEditInvProduct,
    saveInvCategory: inv.saveInvCategory,
    deleteInvCategory: inv.deleteInvCategory,
    openEditInvCategory: inv.openEditInvCategory,
    saveInvMovement: inv.saveInvMovement,
    deleteInvMovement: inv.deleteInvMovement,
    saveInvTransfer: inv.saveInvTransfer,
    deleteInvTransfer: inv.deleteInvTransfer,
    getInvCategoryName: inv.getInvCategoryName,
    getInvCategoryColor: inv.getInvCategoryColor,
    getInvProductName: inv.getInvProductName,
    saveMeeting: cal.saveMeeting,
    deleteMeeting: cal.deleteMeeting,
    openEditMeeting: cal.openEditMeeting,
    openProject: fs.openProject,
    saveGalleryPhoto: gal.saveGalleryPhoto,
    deleteGalleryPhoto: gal.deleteGalleryPhoto,
    handleGalleryImageSelect: gal.handleGalleryImageSelect,
    handleInvProductImageSelect: inv.handleInvProductImageSelect,
    openLightbox: gal.openLightbox,
    closeLightbox: gal.closeLightbox,
    lightboxPrev: gal.lightboxPrev,
    lightboxNext: gal.lightboxNext,
    getFilteredGalleryPhotos: gal.getFilteredGalleryPhotos,
    startTimeTracking: tt.startTimeTracking,
    stopTimeTracking: tt.stopTimeTracking,
    saveManualTimeEntry: tt.saveManualTimeEntry,
    openNewInvoice: invCtx.openNewInvoice,
    updateInvoiceItem: invCtx.updateInvoiceItem,
    addInvoiceItem: invCtx.addInvoiceItem,
    removeInvoiceItem: invCtx.removeInvoiceItem,
    saveInvoice: invCtx.saveInvoice,
    postComment: fs.postComment,
    fileToBase64: fs.fileToBase64,

    // Computed
    currentProject: fs.currentProject,
    pendingCount: fs.pendingCount,
    activeTasks: fs.activeTasks,
    completedTasks: fs.completedTasks,
    overdueTasks: fs.overdueTasks,
    urgentTasks: fs.urgentTasks,
    adminFilteredTasks: fs.adminFilteredTasks,
    projectExpenses: fs.projectExpenses,
    projectTasks: fs.projectTasks,
    projectBudget: fs.projectBudget,
    projectSpent: fs.projectSpent,
    invTotalValue: inv.invTotalValue,
    invLowStock: inv.invLowStock,
    invTotalStock: inv.invTotalStock,
    invPendingTransfers: inv.invPendingTransfers,
    invAlerts: inv.invAlerts,

    // Gantt
    GANTT_DAYS: fs.GANTT_DAYS,
    GANTT_DAY_NAMES: fs.GANTT_DAY_NAMES,
    GANTT_STATUS_CFG: fs.GANTT_STATUS_CFG,
    GANTT_PRIO_CFG: fs.GANTT_PRIO_CFG,
    getMonday: fs.getMonday,
    getGanttDays: fs.getGanttDays,
    getTaskBar: fs.getTaskBar,
    buildGanttRows: fs.buildGanttRows,
    findOverlaps: fs.findOverlaps,
    getProjectColor: fs.getProjectColor,
    getProjectColorLight: fs.getProjectColorLight,
    calcGanttDays: fs.calcGanttDays,
    calcGanttOffset: fs.calcGanttOffset,

    // ===== CHAT =====
    messages: chat.messages,
    setMessages: chat.setMessages,
    chatProjectId: chat.chatProjectId,
    setChatProjectId: chat.setChatProjectId,
    chatDmUser: chat.chatDmUser,
    setChatDmUser: chat.setChatDmUser,
    isRecording: chat.isRecording,
    setIsRecording: chat.setIsRecording,
    isSavingTask: chat.isSavingTask,
    setIsSavingTask: chat.setIsSavingTask,
    recDuration: chat.recDuration,
    setRecDuration: chat.setRecDuration,
    recVolume: chat.recVolume,
    setRecVolume: chat.setRecVolume,
    audioPreviewUrl: chat.audioPreviewUrl,
    setAudioPreviewUrl: chat.setAudioPreviewUrl,
    audioPreviewDuration: chat.audioPreviewDuration,
    setAudioPreviewDuration: chat.setAudioPreviewDuration,
    pendingFiles: chat.pendingFiles,
    setPendingFiles: chat.setPendingFiles,
    chatDropActive: chat.chatDropActive,
    setChatDropActive: chat.setChatDropActive,
    mediaRecRef: chat.mediaRecRef,
    audioChunksRef: chat.audioChunksRef,
    audioStreamRef: chat.audioStreamRef,
    analyserRef: chat.analyserRef,
    recTimerRef: chat.recTimerRef,
    recAnimRef: chat.recAnimRef,
    fileInputRef: chat.fileInputRef,
    audioPreviewBlobRef: chat.audioPreviewBlobRef,
    playingAudioRef: chat.playingAudioRef,
    playingAudio: chat.playingAudio,
    setPlayingAudio: chat.setPlayingAudio,
    audioProgress: chat.audioProgress,
    setAudioProgress: chat.setAudioProgress,
    audioCurrentTime: chat.audioCurrentTime,
    setAudioCurrentTime: chat.setAudioCurrentTime,
    showEmojiPicker: chat.showEmojiPicker,
    setShowEmojiPicker: chat.setShowEmojiPicker,
    chatReplyingTo: chat.chatReplyingTo,
    setChatReplyingTo: chat.setChatReplyingTo,
    messageReactions: chat.messageReactions,
    setMessageReactions: chat.setMessageReactions,
    typingUsers: chat.typingUsers,
    setTypingUsers: chat.setTypingUsers,
    chatMenuMsg: chat.chatMenuMsg,
    setChatMenuMsg: chat.setChatMenuMsg,
    chatMsgSearch: chat.chatMsgSearch,
    setChatMsgSearch: chat.setChatMsgSearch,
    sendMessage: chat.sendMessage,
    startRecording: chat.startRecording,
    stopRecording: chat.stopRecording,
    cancelRecording: chat.cancelRecording,
    handleMicButton: chat.handleMicButton,
    sendVoiceNote: chat.sendVoiceNote,
    handleFileSelect: chat.handleFileSelect,
    removePendingFile: chat.removePendingFile,
    sendPendingFiles: chat.sendPendingFiles,
    sendAll: chat.sendAll,
    toggleReaction: chat.toggleReaction,
    deleteMessage: chat.deleteMessage,
    copyMessageText: chat.copyMessageText,
    toggleAudioPlay: chat.toggleAudioPlay,
    fmtRecTime: chat.fmtRecTime,
    fileIcon: chat.fileIcon,
    fmtFileSize: chat.fmtFileSize,

    // Task CRUD (in FirestoreContext but saveTask also uses chat.isSavingTask)
    saveTask: fs.saveTask,
    openEditTask: fs.openEditTask,

    // ===== NOTIFICATIONS =====
    notifPermission: notif.notifPermission,
    setNotifPermission: notif.setNotifPermission,
    notifHistory: notif.notifHistory,
    setNotifHistory: notif.setNotifHistory,
    notifPrefs: notif.notifPrefs,
    setNotifPrefs: notif.setNotifPrefs,
    showNotifPanel: notif.showNotifPanel,
    setShowNotifPanel: notif.setShowNotifPanel,
    unreadCount: notif.unreadCount,
    notifSound: notif.notifSound,
    setNotifSound: notif.setNotifSound,
    inAppNotifs: notif.inAppNotifs,
    setInAppNotifs: notif.setInAppNotifs,
    notifFilterCat: notif.notifFilterCat,
    setNotifFilterCat: notif.setNotifFilterCat,
    showNotifBanner: notif.showNotifBanner,
    setShowNotifBanner: notif.setShowNotifBanner,
    requestNotifPermission: notif.requestNotifPermission,
    dismissNotifBanner: notif.dismissNotifBanner,
    markNotifRead: notif.markNotifRead,
    markAllNotifRead: notif.markAllNotifRead,
    clearNotifHistory: notif.clearNotifHistory,
    toggleNotifPref: notif.toggleNotifPref,
    sendNotif: notif.sendNotif,
    sendBrowserNotif: notif.sendBrowserNotif,
  };
}
